---
title: "Week1_2_3 check on data"
author: "Jackie Ouzman"
date: "6 August 2019"
output: html_document
---

```{r setup install package1, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(readxl)

library(ggplot2)
library(readr)
library(sp)
library(biogeo)
library(stringr)
library(rgdal)
library(sf)

library(gganimate)
library(png)
library(gifski)

knitr::opts_chunk$set(include = FALSE)
```



# 4. Now I need to view each day collar to work out when the collars failed.
I have done this using the filter function and then check out the distance from fence.

Day 1 20/5/2019
Fence 1 and 2

```{r inspect data to view quaility day1}
dim(Check_df_VF_week1_2_3_InclusionBord_c_animalID)
head(Check_df_VF_week1_2_3_InclusionBord_c_animalID,3)

Inclusion_20_05_2019 <- Check_df_VF_week1_2_3_InclusionBord_c_animalID %>% 
  filter(date == "2019-05-20") 

Inclusion_Dist20_05 <-  ggplot(Inclusion_20_05_2019, aes(x = hms, y = value, colour = collar))+
  geom_point()+
  facet_wrap(.~animal_ID)+
  geom_hline(yintercept = 0)+
  theme(axis.text.x=element_text(angle=90,hjust=1),
        legend.position = "none")+
  labs(title= "Week1 2019-05-20",
       x= "Time of day",
       y = "Distance (m) from VF")
Inclusion_Dist20_05
ggsave(filename = "Inclusion_Dist20_05.png", device = "png" )

x_yInclusion_Dist20_05 <- ggplot() +
  geom_sf(data = eden_valley, color = "black", fill = NA) +
  geom_sf(data = fence1, color = "grey") +
  geom_sf(data = fence2, color = "grey") +
  geom_point(data = Inclusion_20_05_2019, aes(POINT_X, POINT_Y,colour = animal_ID), inherit.aes = FALSE, alpha = 0.01) +
  facet_wrap(.~animal_ID)+
  theme_bw()+
  theme(legend.position = "none",
        axis.text.x=element_blank(),
        axis.text.y=element_blank())+
  labs(title= "Fence 1 and 2 with data from 2019-05-20")
x_yInclusion_Dist20_05

ggsave(filename = "x_yInclusion_Dist20_05.png", device = "png" ,dpi=600)
  
```
```{r inspect data to view quaility day2}


Inclusion_21_05_2019 <- Check_df_VF_week1_2_3_InclusionBord_c_animalID %>% 
  filter(date == "2019-05-21") 

Inclusion_Dist21_05 <-  ggplot(Inclusion_21_05_2019, aes(x = hms, y = value, colour = collar))+
  geom_point()+
  facet_wrap(.~animal_ID)+
  geom_hline(yintercept = 0)+
  theme(axis.text.x=element_text(angle=90,hjust=1),
        legend.position = "none")+
  labs(title= "Week1 2019-05-21",
       x= "Time of day",
       y = "Distance (m) from VF")
Inclusion_Dist20_05
ggsave(filename = "Inclusion_Dist21_05.png", device = "png" )

x_yInclusion_Dist21_05 <- ggplot() +
  geom_sf(data = eden_valley, color = "black", fill = NA) +
  geom_sf(data = fence1, color = "grey") +
  geom_sf(data = fence2, color = "grey") +
  geom_point(data = Inclusion_21_05_2019, aes(POINT_X, POINT_Y,colour = animal_ID), inherit.aes = FALSE, alpha = 0.01) +
  facet_wrap(.~animal_ID)+
  theme_bw()+
  theme(legend.position = "none",
        axis.text.x=element_blank(),
        axis.text.y=element_blank())+
  labs(title= "Fence 1 and 2 with data from 2019-05-20")
x_yInclusion_Dist21_05

ggsave(filename = "x_yInclusion_Dist21_05.png", device = "png" ,dpi=600)
  
```



Other options with the inclusion data
```{r filter postive values and summaries with plots}

Inclusion_20_21_05_2019 <- Check_df_VF_week1_2_3_InclusionBord_c_animalID %>% 
  filter(date == "2019-05-21" | date == "2019-05-20" )
#head(Inclusion_20_21_05_2019)
summary(df_VF_week1_2_3_InclusionBord_c_animalID$time)

Inclusion_week1 <- filter(df_VF_week1_2_3_InclusionBord_c_animalID, 
                                                  between(time, as_datetime('2019-05-20 12:30:01', tz="GMT"),
                                                         as_datetime('2019-05-27 24:00:00', tz="GMT")))
                                                 
#head(Inclusion_week1)
Inclusion_week1_positive <- Inclusion_week1 %>% 
  filter(value >=0 )
 

Inclusion_week1_positive1 <- group_by(Inclusion_week1_positive,
                             day, animal_ID) %>%   
                    summarise(count = n())
                    

#change the day to factor
Inclusion_week1_positive1$day_factor <- as.factor(Inclusion_week1_positive1$day)


ggplot(Inclusion_week1_positive1, aes(x = day_factor, y = count))+
  geom_boxplot(alpha = 0.2)+
  geom_point()+
  theme_bw()+
  #facet_wrap(.~animal_ID)+
  geom_vline(xintercept = c(1,4),color = "blue", size=0.5)+ #this is the order which it appears on the axis can add 1.3 values too!
  theme(axis.text.x=element_text(angle=90,hjust=1))+
        #,legend.position = "none")+
  labs(title= "Week1",
       x= "Day",
       y = "Counts of logged activity inside exclusion zone")


```

